// -------------------------------------------------------------
// 
// File Name: hdlsrc\Laba1_2\Subsystem.v
// Created: 2022-10-18 20:02:47
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// o_Y                           ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem
// Source Path: Laba1_2/Subsystem
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem
          (i_CLK,
           i_RST_N,
           i_CLK_EN,
           i_W0,
           i_W1,
           i_W2,
           i_W3,
           i_X0,
           i_X1,
           i_X2,
           i_X3,
           ce_out,
           o_Y);


  input   i_CLK;
  input   i_RST_N;
  input   i_CLK_EN;
  input   signed [7:0] i_W0;  // int8
  input   signed [7:0] i_W1;  // int8
  input   signed [7:0] i_W2;  // int8
  input   signed [7:0] i_W3;  // int8
  input   signed [7:0] i_X0;  // int8
  input   signed [7:0] i_X1;  // int8
  input   signed [7:0] i_X2;  // int8
  input   signed [7:0] i_X3;  // int8
  output  ce_out;
  output  signed [17:0] o_Y;  // sfix18


  wire enb;
  reg signed [7:0] Unit_Delay_out1;  // int8
  reg signed [7:0] Unit_Delay1_out1;  // int8
  reg signed [7:0] Unit_Delay2_out1;  // int8
  reg signed [7:0] Unit_Delay3_out1;  // int8
  reg signed [7:0] Unit_Delay4_out1;  // int8
  wire signed [15:0] Product_out1;  // int16
  reg signed [7:0] Unit_Delay5_out1;  // int8
  wire signed [15:0] Product1_out1;  // int16
  wire signed [16:0] Add_stage2_1;  // sfix17
  wire signed [16:0] Add_stage2_2;  // sfix17
  wire signed [16:0] Add_op_stage1;  // sfix17
  reg signed [7:0] Unit_Delay6_out1;  // int8
  wire signed [15:0] Product2_out1;  // int16
  wire signed [17:0] Add_stage3_1;  // sfix18
  wire signed [17:0] Add_stage3_2;  // sfix18
  wire signed [17:0] Add_op_stage2;  // sfix18
  reg signed [7:0] Unit_Delay7_out1;  // int8
  wire signed [15:0] Product3_out1;  // int16
  wire signed [17:0] Add_stage4_1;  // sfix18
  wire signed [17:0] Add_out1;  // sfix18
  reg signed [17:0] Unit_Delay8_out1;  // sfix18


  assign enb = i_CLK_EN;

  always @(posedge i_CLK or negedge i_RST_N)
    begin : Unit_Delay_process
      if (i_RST_N == 1'b0) begin
        Unit_Delay_out1 <= 8'sb00000000;
      end
      else begin
        if (enb) begin
          Unit_Delay_out1 <= i_W0;
        end
      end
    end



  always @(posedge i_CLK or negedge i_RST_N)
    begin : Unit_Delay1_process
      if (i_RST_N == 1'b0) begin
        Unit_Delay1_out1 <= 8'sb00000000;
      end
      else begin
        if (enb) begin
          Unit_Delay1_out1 <= i_W1;
        end
      end
    end



  always @(posedge i_CLK or negedge i_RST_N)
    begin : Unit_Delay2_process
      if (i_RST_N == 1'b0) begin
        Unit_Delay2_out1 <= 8'sb00000000;
      end
      else begin
        if (enb) begin
          Unit_Delay2_out1 <= i_W2;
        end
      end
    end



  always @(posedge i_CLK or negedge i_RST_N)
    begin : Unit_Delay3_process
      if (i_RST_N == 1'b0) begin
        Unit_Delay3_out1 <= 8'sb00000000;
      end
      else begin
        if (enb) begin
          Unit_Delay3_out1 <= i_W3;
        end
      end
    end



  always @(posedge i_CLK or negedge i_RST_N)
    begin : Unit_Delay4_process
      if (i_RST_N == 1'b0) begin
        Unit_Delay4_out1 <= 8'sb00000000;
      end
      else begin
        if (enb) begin
          Unit_Delay4_out1 <= i_X0;
        end
      end
    end



  assign Product_out1 = Unit_Delay_out1 * Unit_Delay4_out1;



  always @(posedge i_CLK or negedge i_RST_N)
    begin : Unit_Delay5_process
      if (i_RST_N == 1'b0) begin
        Unit_Delay5_out1 <= 8'sb00000000;
      end
      else begin
        if (enb) begin
          Unit_Delay5_out1 <= i_X1;
        end
      end
    end



  assign Product1_out1 = Unit_Delay1_out1 * Unit_Delay5_out1;



  assign Add_stage2_1 = {Product_out1[15], Product_out1};
  assign Add_stage2_2 = {Product1_out1[15], Product1_out1};
  assign Add_op_stage1 = Add_stage2_1 + Add_stage2_2;



  always @(posedge i_CLK or negedge i_RST_N)
    begin : Unit_Delay6_process
      if (i_RST_N == 1'b0) begin
        Unit_Delay6_out1 <= 8'sb00000000;
      end
      else begin
        if (enb) begin
          Unit_Delay6_out1 <= i_X2;
        end
      end
    end



  assign Product2_out1 = Unit_Delay2_out1 * Unit_Delay6_out1;



  assign Add_stage3_1 = {Add_op_stage1[16], Add_op_stage1};
  assign Add_stage3_2 = {{2{Product2_out1[15]}}, Product2_out1};
  assign Add_op_stage2 = Add_stage3_1 + Add_stage3_2;



  always @(posedge i_CLK or negedge i_RST_N)
    begin : Unit_Delay7_process
      if (i_RST_N == 1'b0) begin
        Unit_Delay7_out1 <= 8'sb00000000;
      end
      else begin
        if (enb) begin
          Unit_Delay7_out1 <= i_X3;
        end
      end
    end



  assign Product3_out1 = Unit_Delay3_out1 * Unit_Delay7_out1;



  assign Add_stage4_1 = {{2{Product3_out1[15]}}, Product3_out1};
  assign Add_out1 = Add_op_stage2 + Add_stage4_1;



  always @(posedge i_CLK or negedge i_RST_N)
    begin : Unit_Delay8_process
      if (i_RST_N == 1'b0) begin
        Unit_Delay8_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay8_out1 <= Add_out1;
        end
      end
    end



  assign o_Y = Unit_Delay8_out1;

  assign ce_out = i_CLK_EN;

endmodule  // Subsystem

